[package]
name = "hermit_bench_output"
authors = ["Carl Wachter <carl.wachter@rwth-aachen.de>"]
version = "0.1.1"
edition = "2021"
description = "A library to interface to the hermit-bench benchmarking framework."
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
